x-dev-build: &dev-build
  context: .
  dockerfile: Dockerfile
  target: dev

services:
  development:
    build: *dev-build
    container_name: rock-paper-scissors
    stdin_open: true   # Keep STDIN open for CLI interaction
    tty: true          # Allocate a pseudo-TTY
    command: ["app"]
    volumes:
      - .:/app
    working_dir: /app

  test:
    build: *dev-build
    container_name: rock-paper-scissors-tests
    command: ["go", "test", "-shuffle=on", "-cover", "./..."]

  light:
    build:
      context: .
      dockerfile: Dockerfile
      target: alpine-app
    container_name: rock-paper-scissors-light
    stdin_open: true   # Keep STDIN open for CLI interaction
    tty: true          # Allocate a pseudo-TTY
    command: [ "./app" ]

